# Generated by Django 4.2.20 on 2025-04-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0017_remove_passengerhistory_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerhistory',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
    ]
