# Generated by Django 4.2.20 on 2025-04-17 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0018_passengerhistory_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengerhistory',
            name='mobile',
        ),
    ]
