# Generated by Django 4.2.20 on 2025-04-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0019_remove_passengerhistory_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcode',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
    ]
