# Generated by Django 4.2.20 on 2025-04-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0021_alter_ticketcode_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcode',
            name='mobile',
            field=models.IntegerField(default=9000000000, max_length=10),
        ),
    ]
