# Generated by Django 4.2.20 on 2025-04-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0022_alter_ticketcode_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcode',
            name='mobile',
            field=models.TextField(default='000000000'),
        ),
    ]
