# Generated by Django 4.2.20 on 2025-04-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0023_alter_ticketcode_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerhistory',
            name='usermobile',
            field=models.TextField(default='000000000'),
        ),
    ]
