# Generated by Django 4.2.20 on 2025-04-17 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0024_passengerhistory_usermobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passengerhistory',
            old_name='usermobile',
            new_name='mobile',
        ),
    ]
